services:
  spring01:
    build: ./was
    ports:
      - "8081:8080"
  spring02:
    build: ./was
    ports:
      - "8082:8080"
  nginx:
    build: ./webServer
    ports:
      - "80:80"
    volumes:
      - D:\dockerTest\compose\02\webServer\etcNginx\nginx.conf:/etc/nginx/nginx.conf
      - D:\dockerTest\compose\02\webServer\etcNginx\conf.d\default.conf:/etc/nginx/conf.d/default.conf
  mysql:
    container_name: mysql-container-sp
    build: ./DB
    ports:
      - "3307:3306"
    volumes:
      - D:\dockerTest\compose\02\DB\data:/var/lib/mysql