services:
  spring01:
    build: ./was
    ports:
      - "8081:8080"
  spring02:
    build: ./was
    ports:
      - "8082:8080"
  nginx:
    build: ./webServer
    ports:
      - "80:80"
  mysql:
    container_name: mysql-image-sp
    build: ./DB
    ports:
      - "3307:3306"